### ISSUE TITLE
Adam performance would be affected in mixed precision mode?

### ISSUE THREAD

**Issue by syorami** [suvojit-0x55aa/mixed-precision-pytorch#2]
Thanks for your sharing and this solves my long-existing problem. However, when I change default optimizer from SGDM to Adam in half-precision mode, I find that Adam does not outperform SGDM even in the early stage. And without mixed training, I could notice a performance boost in Adam performance. Is this because of default Adam implementation not compatible with fp16 or just my improper hyperparameter setting? I would appreciate your clarification.

**Comment by suvojit-0x55aa** [comment]
Hi @tmac1997 it's good to hear that this project could help you.

FP16 suffers from numerical instability when small updates are taking place. Adam has few such updates that makes it more unstable. One trick is to check for the `epsilon` value which is normally set to `1e-8` or `1e-7`, those values being unrepresentable in FP16, try changing it to suit the situation. If that doesn't work you can do the Adam updates totally on FP32 master copy as show here [ajbrock/FP16 Adam for PyTorch](https://gist.github.com/ajbrock/075c0ca4036dc4d8581990a6e76e07a3).

**Comment by syorami** [comment]
Thanks, I would have a try!
