### ISSUE TITLE
Speed test on Volta Cores

### ISSUE THREAD

**Issue by blueardour** [suvojit-0x55aa/mixed-precision-pytorch#4]
Good project @suvojit-0x55aa, specially the benchmark of memory usage and speed.

One question: As far as I know the Pascal GPU has no volta core inside, while GPUs like 2080TI, V100 equip with that. The difference is not big for FP32 computing but brings a big margin for FP16 computing.  From current experiments, the mixed precision version seemed not so siginificant in speed that the FP32 versions. I wonder if it's the same for GPUs such as 2080TI and V100?

**Comment by suvojit-0x55aa** [comment]
Thanks this could help you @blueardour 
I'm planning on doing a benchmark as soon as I get my hands on V100 or 2080Ti machine. nVidia does claim their Volta and Turing architecture speeds up training 

> NVIDIA GPUs offer up to 8x more half precision arithmetic throughput when compared to single-precision, thus speeding up math-limited layers.

Also [this article](https://hackernoon.com/rtx-2080ti-vs-gtx-1080ti-fastai-mixed-precision-training-comparisons-on-cifar-100-761d8f615d7f) by [Sanyam Bhutani](https://hackernoon.com/@init_27) reports that mixed precision on 2080Ti is *35 %* faster than 1080Ti.

**Comment by suvojit-0x55aa** [comment]
New [benchmarks](https://github.com/suvojit-0x55aa/mixed-precision-pytorch/blob/master/README.md#results) added for Volta GPUs.

**Comment by blueardour** [comment]
Great. It seems to be quite attrictive to employ mix precision training on Volta cores.
